### PR TITLE
Add Labels as an alternative to titles 

### PR DESCRIPTION
**Pull request by danielo515**
This is related with #8

### CODE REVIEW

**Comment by felixhayashi** [comment]
Thanks Danielo, fixed as mentioned in #8

**Comment by tobibeer** [comment]
Maybe use `caption` instead?

**Comment by felixhayashi** [comment]
When daniolo proposed this more than a month ago, tiddlymap didn't allow captions to be used. Now it does :)

**Comment by tobibeer** [comment]
:+1:

**Pull request closed without merging**
