### PR TITLE
clarify node.js install instructions

### PR DESCRIPTION
**Pull request by rcrath**
as per https://github.com/felixhayashi/TW5-TiddlyMap/issues/98#issuecomment-90863929

### CODE REVIEW

**Comment by felixhayashi** [comment]
Thanks @rcrath!

Would you please sign the [contributors list](https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/CONTRIBUTING.md) first, so I can accept your pull request? Thanks

-Felix

**Comment by rcrath** [comment]
@felixhayashi , done, I think.

**Comment by felixhayashi** [comment]
Hi @rcrath sorry, I cannot see the pull request to the CLA (https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/licenses/CLA-INDIVIDUAL.md) :( The only pull I see is this one (https://github.com/felixhayashi/TW5-TiddlyMap/pulls). Could you please verify it? Thanks

**Comment by felixhayashi** [comment]
> This is my first contri to someone else's repositiory.

Thank you :)

> Still trying to get my head around github.

Yeah, it took me a while too to understand how github works. But it is really nice. Especially when hosting open source stuff. You can also host your wiki using github (like I do with the tiddlymap demo site).

**Comment by alecperkey** [comment]
just to be clear?  since i have nodejs auto save my tw 5.1.14 changes, do I need to follow any of the UI warning (save and refresh?)

I have been refreshing just to be safe but if on node, we shouldn't need to show that message, right?
https://i.imgur.com/YahDTHo.png

**Comment by alecperkey** [comment]
maybe I have to refresh for them so start working, but if I import 15 plugins, one at a time, can I just refresh at the end? are there possibilities some plugins cause bugs with this route?

**Comment by felixhayashi** [comment]
> I have been refreshing just to be safe but if on node, we shouldn't need to show that message, right?

autosave will just save it but you need to refresh your browser in any case so change will have an effect.

> but if I import 15 plugins, one at a time, can I just refresh at the end?

yes, that's totally fine.

**Pull request merged**
